sudo: false
dist: trusty
language: rust

rust:
- stable
- nightly

matrix:
  allow_failures:
  - rust: nightly

install:
- rustup component add clippy rustfmt

script:
- cargo build
- cargo test
- cargo clippy -- -Dwarnings
- cargo fmt --all -- --check
